
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class minifacebook extends javax.swing.JFrame {

    /**
     * Creates new form minifacebook
     */
    public minifacebook() {
        initComponents();
        Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(100, 100, 0);
        lb_foto.setIcon(new ImageIcon(img));
        dt_fecha.setDate(new Date());
        this.setLocationRelativeTo(null);
        cargarrarchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_inicio = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ver = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jif_enviar = new javax.swing.JInternalFrame();
        jp_enviar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_mensajeenviar = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        cb_enviarmensaje = new javax.swing.JComboBox<>();
        jp_verMensaje = new javax.swing.JPanel();
        cb_vermensajes = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_ver = new javax.swing.JTable();
        jMenuItem4 = new javax.swing.JMenuItem();
        jp_buscar = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_buscar = new javax.swing.JTable();
        jp_solicitudes = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_solicitudes = new javax.swing.JTable();
        jp_amigos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jp_publicar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_publicar = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        lb_publicar = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jsc_muro = new javax.swing.JScrollPane();
        jp_post = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        pf_login = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_contra = new javax.swing.JPasswordField();
        tf_nick = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_pais = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dt_fecha = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        jMenuItem2.setText("Muro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem9.setText("Publicar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem3.setText("Notificaciones");
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mensajes");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Enviar mensajes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        ver.setText("Ver mensajes");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        jMenu2.add(ver);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Amigos");

        jMenuItem6.setText("Buscar amigos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Solicitudes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Amigos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jd_inicio.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_inicioLayout = new javax.swing.GroupLayout(jd_inicio.getContentPane());
        jd_inicio.getContentPane().setLayout(jd_inicioLayout);
        jd_inicioLayout.setHorizontalGroup(
            jd_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_inicioLayout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_inicioLayout.setVerticalGroup(
            jd_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jif_enviar.setMaximizable(true);
        jif_enviar.setVisible(true);

        javax.swing.GroupLayout jif_enviarLayout = new javax.swing.GroupLayout(jif_enviar.getContentPane());
        jif_enviar.getContentPane().setLayout(jif_enviarLayout);
        jif_enviarLayout.setHorizontalGroup(
            jif_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jif_enviarLayout.setVerticalGroup(
            jif_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jLabel10.setText("Usuario");

        jLabel11.setText("Mensaje");

        ta_mensajeenviar.setColumns(20);
        ta_mensajeenviar.setRows(5);
        jScrollPane1.setViewportView(ta_mensajeenviar);

        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_enviarLayout = new javax.swing.GroupLayout(jp_enviar);
        jp_enviar.setLayout(jp_enviarLayout);
        jp_enviarLayout.setHorizontalGroup(
            jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_enviarLayout.createSequentialGroup()
                .addGroup(jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_enviarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(cb_enviarmensaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jp_enviarLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton4)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jp_enviarLayout.setVerticalGroup(
            jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_enviarLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_enviarmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_enviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        cb_vermensajes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_vermensajesItemStateChanged(evt);
            }
        });
        cb_vermensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vermensajesActionPerformed(evt);
            }
        });

        jt_ver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mensaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_ver);

        javax.swing.GroupLayout jp_verMensajeLayout = new javax.swing.GroupLayout(jp_verMensaje);
        jp_verMensaje.setLayout(jp_verMensajeLayout);
        jp_verMensajeLayout.setHorizontalGroup(
            jp_verMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_verMensajeLayout.createSequentialGroup()
                .addGroup(jp_verMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_verMensajeLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(cb_vermensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_verMensajeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jp_verMensajeLayout.setVerticalGroup(
            jp_verMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_verMensajeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cb_vermensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jMenuItem4.setText("jMenuItem4");

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jt_buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sugerencia"
            }
        ));
        jt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_buscarMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jt_buscar);

        javax.swing.GroupLayout jp_buscarLayout = new javax.swing.GroupLayout(jp_buscar);
        jp_buscar.setLayout(jp_buscarLayout);
        jp_buscarLayout.setHorizontalGroup(
            jp_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buscarLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_buscarLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jp_buscarLayout.setVerticalGroup(
            jp_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jt_solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emisor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_solicitudesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jt_solicitudes);

        javax.swing.GroupLayout jp_solicitudesLayout = new javax.swing.GroupLayout(jp_solicitudes);
        jp_solicitudes.setLayout(jp_solicitudesLayout);
        jp_solicitudesLayout.setHorizontalGroup(
            jp_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_solicitudesLayout.createSequentialGroup()
                .addGroup(jp_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_solicitudesLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton6)
                        .addGap(88, 88, 88)
                        .addComponent(jButton7))
                    .addGroup(jp_solicitudesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jp_solicitudesLayout.setVerticalGroup(
            jp_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_solicitudesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jl_amigos);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Lista de amigos");

        javax.swing.GroupLayout jp_amigosLayout = new javax.swing.GroupLayout(jp_amigos);
        jp_amigos.setLayout(jp_amigosLayout);
        jp_amigosLayout.setHorizontalGroup(
            jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_amigosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_amigosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jp_amigosLayout.setVerticalGroup(
            jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_amigosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ta_publicar.setColumns(20);
        ta_publicar.setRows(5);
        jScrollPane2.setViewportView(ta_publicar);

        jLabel14.setText("Estado");

        jButton8.setText("Agregar imagen");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Publicar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_publicarLayout = new javax.swing.GroupLayout(jp_publicar);
        jp_publicar.setLayout(jp_publicarLayout);
        jp_publicarLayout.setHorizontalGroup(
            jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_publicarLayout.createSequentialGroup()
                .addGroup(jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_publicarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_publicarLayout.createSequentialGroup()
                        .addGroup(jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_publicarLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton8)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_publicarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)))
                        .addComponent(lb_publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jp_publicarLayout.setVerticalGroup(
            jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_publicarLayout.createSequentialGroup()
                .addGroup(jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_publicarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel14))
                    .addGroup(jp_publicarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jp_publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_publicarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jp_publicarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(33, 33, 33))))
        );

        jsc_muro.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jsc_muro.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jsc_muro.setAutoscrolls(true);

        jp_post.setPreferredSize(new java.awt.Dimension(563, 9000));

        javax.swing.GroupLayout jp_postLayout = new javax.swing.GroupLayout(jp_post);
        jp_post.setLayout(jp_postLayout);
        jp_postLayout.setHorizontalGroup(
            jp_postLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jp_postLayout.setVerticalGroup(
            jp_postLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9000, Short.MAX_VALUE)
        );

        jsc_muro.setViewportView(jp_post);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Sistema de registro MiniFacebook");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre completo");

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Nickname");

        pf_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_contraActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contraseña");

        cb_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honduras", "Estados Unidos", "Mexico", "Canada", "Rusia", "Argentina", "Brasil", "Nicaragua", "El Salvador", "Costa Rica" }));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pais");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Creacion de usuario");

        jLabel9.setText("Fecha de nacimiento");

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Seleccionar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel13.setText("Imagen de perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_contra)
                            .addComponent(tf_nombre)
                            .addComponent(tf_nick)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(cb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(dt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean ingreso = false;
        try {
            String nickname = tf_usuario.getText();
            String contra = pf_login.getText();
            System.out.println(lista);
            for (Usuario us : lista) {
                if (us.getNickname().equals(nickname) && us.getPassword().equals(contra)) {
                    JOptionPane.showMessageDialog(this, "Ingreso con exito");
                    DefaultComboBoxModel model = new DefaultComboBoxModel(lista.toArray());
                    cb_enviarmensaje.setModel(model);
                    use = us;
                    setUse(us);
                    System.out.println(us.getSolicitudes());
                    System.out.println(use.getMuro().size());
                    tf_usuario.setText("");
                    pf_login.setText("");
                    ingreso = true;
                    this.dispose();
                    jd_inicio.setModal(true);
                    jd_inicio.pack();
                    jd_inicio.setLocationRelativeTo(this);
                    jd_inicio.setSize(500, 500);
                    jd_inicio.setVisible(true);
                }
            }
            if (!ingreso) {
                JOptionPane.showMessageDialog(this, "Contraseña o nickname invalido");
                tf_usuario.setText("");
                pf_login.setText("");
            }
        } catch (Exception e) {
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void pf_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_contraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String nombre = tf_nombre.getText();
            String nick = tf_nick.getText();
            String password = pf_contra.getText();
            String fecha = dt_fecha.getDate().toString();
            String pais = cb_pais.getSelectedItem().toString();
            Icon foto = lb_foto.getIcon();
            Usuario user = new Usuario(nombre, nick, password, fecha, pais, foto);
            lista.add(user);
            agregararchivo(user);
            tf_nombre.setText("");
            tf_nick.setText("");
            pf_contra.setText("");
            Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(100, 100, 0);
            lb_foto.setIcon(new ImageIcon(img));
            dt_fecha.setDate(new Date());
            JOptionPane.showMessageDialog(this, "Se creo la cuenta");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        //  cb_vermensajes = new JComboBox();
        try {
            cb_vermensajes.removeAllItems();
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_vermensajes.getModel();
            ArrayList<String> list = new ArrayList();
            for (Mensaje m : use.getMensajes()) {
                if (!list.contains(m.getEmisor())) {
                    list.add(m.getEmisor());
                    model.addElement(m.getEmisor());
                }
            }
            cb_vermensajes.setModel(model);
            jif_enviar.setContentPane(jp_verMensaje);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_enviar.setVisible(true);
            jd_inicio.repaint();
            //jd_inicio.add(jDesktopPane1);
            jif_enviar.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_verActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            //jif_enviar.add(jp_enviar);
            jif_enviar.setContentPane(jp_enviar);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_enviar.setVisible(true);
            jd_inicio.repaint();
            jif_enviar.setVisible(true);
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Usuario us = (Usuario) cb_enviarmensaje.getSelectedItem();
            String mensaje = ta_mensajeenviar.getText();
            Mensaje m = new Mensaje(use.getNickname(), us.getNickname(), mensaje);
            ta_mensajeenviar.setText("");
            for (Usuario u : lista) {
                if (u == us || u == use) {
                    u.getMensajes().add(m);
                }
            }
            for (Usuario usex : lista) {
                agregar_archivo(usex);
            }
            
        } catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb_vermensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vermensajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_vermensajesActionPerformed

    private void cb_vermensajesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_vermensajesItemStateChanged
        
        if (evt.getStateChange() == 1) {
            
            DefaultTableModel mod = (DefaultTableModel) jt_ver.getModel();
            String emisor = cb_vermensajes.getSelectedItem().toString();
            for (Mensaje me : use.getMensajes()) {
                if (me.getEmisor().equals(emisor)) {
                    String[] row = {me.getMesaje()};
                    mod.addRow(row);
                }
            }
            jt_ver.setModel(mod);
            jd_inicio.repaint();
            
        } else {
            DefaultTableModel modeo = (DefaultTableModel) jt_ver.getModel();
            for (int i = 0; i < modeo.getRowCount(); i++) {
                modeo.removeRow(i);
                i -= 1;
            }
            
        }

    }//GEN-LAST:event_cb_vermensajesItemStateChanged

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        if (use.getSolicitudes().size() > 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) jt_solicitudes.getModel();
                for (Solicitudes us : use.getSolicitudes()) {
                    if (us.getEmisor() != use) {
                        
                        Object[] so = {us};
                        System.out.println(Arrays.toString(so));
                        model.addRow(so);
                        listasolicitud.add(us);
                    }
                }
                jt_solicitudes.setModel(model);
                jt_solicitudes.repaint();
            } catch (Exception e) {
            }
        }
        try {

            //jif_enviar.add(jp_enviar);
            jif_enviar.setContentPane(jp_solicitudes);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_solicitudes.setVisible(true);
            jd_inicio.repaint();
            //jd_inicio.add(jDesktopPane1);
            //jif_enviar.setVisible(true);
        } catch (Exception e) {
            
        }
        

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jepg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_foto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        if (lista.size() - 1 > (use.getAmigos().size()) + use.getSolicitudes().size()) {
            DefaultTableModel model = (DefaultTableModel) jt_buscar.getModel();
            for (Usuario us : lista) {
                if (us != use) {
                    if (use.getAmigos().size() < 1 && use.getSolicitudes().size() < 1) {
                        Object[] p = {us};
                        model.addRow(p);
                        listabuscar.add(us);
                    } else {
                        if ((!use.getAmigos().contains(us))) {
                            for (Solicitudes s : use.getSolicitudes()) {
                                if ((!s.getEmisor().equals(us)) && (!s.getReceptor().equals(us)) && (!use.getAmigos().contains(s))) {
                                    Object[] p = {us};
                                    model.addRow(p);
                                    listabuscar.add(us);
                                }
                            }
                        }
                    }
                }
            }
            jt_buscar.setModel(model);
        }
        try {

            //jif_enviar.add(jp_enviar);
            jif_enviar.setContentPane(jp_buscar);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_buscar.setVisible(true);
            jd_inicio.repaint();
            //jd_inicio.add(jDesktopPane1);
            //jif_enviar.setVisible(true);
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        System.out.println(buscar);
        for (Usuario us : lista) {
            if (us == buscar) {
                Solicitudes s = new Solicitudes(use, us);
                us.getSolicitudes().add(s);
                use.getSolicitudes().add(s);
            }
        }
        
        try {
            agregararchivo(use);
        } catch (IOException ex) {
            Logger.getLogger(minifacebook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = (DefaultTableModel) jt_buscar.getModel();
        int rows = jt_buscar.getModel().getRowCount();
        for (int i = 0; i < rows; i++) {
            model.removeRow(0);
        }
        listabuscar.remove(buscar);
        for (Usuario usuario : listabuscar) {
            Usuario[] os = {usuario};
            model.addRow(os);
        }
        jt_buscar.setModel(model);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jd_inicio.dispose();
        use = new Usuario();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            listasolicitud.remove(soli);
            for (Usuario u : lista) {
                if (u == soli.getEmisor()) {
                    u.getAmigos().add(soli.getReceptor());
                } else if (u == soli.getReceptor()) {
                    u.getAmigos().add(soli.getEmisor());
                    u.setSolicitudes(listasolicitud);
                    
                }
            }
        } catch (Exception e) {
        }
        
        try {
            agregar_archivo(use);
        } catch (IOException ex) {
            Logger.getLogger(minifacebook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = (DefaultTableModel) jt_solicitudes.getModel();
        int row = jt_solicitudes.getRowCount();
        for (int i = 0; i < row; i++) {
            ((DefaultTableModel) jt_solicitudes.getModel()).removeRow(0);
        }
        for (Usuario us : lista) {
            if (us == use) {
                for (Solicitudes so : us.getSolicitudes()) {
                    Solicitudes sol[] = {so};
                    model.addRow(sol);
                }
            }
        }
        jt_solicitudes.setModel(model);
        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jt_solicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_solicitudesMouseClicked
        int row = jt_solicitudes.getSelectedRow();
        soli = (Solicitudes) jt_solicitudes.getValueAt(row, 0);
    }//GEN-LAST:event_jt_solicitudesMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jl_amigos.removeAll();
        DefaultListModel model = new DefaultListModel();
        for (Usuario ami : use.getAmigos()) {
            model.addElement(ami);
        }
        jl_amigos.setModel(model);
        try {

            //jif_enviar.add(jp_enviar);
            jif_enviar.setContentPane(jp_amigos);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_amigos.setVisible(true);
            jd_inicio.repaint();
            //jd_inicio.add(jDesktopPane1);
            //jif_enviar.setVisible(true);
        } catch (Exception e) {
            
        }
        

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jt_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_buscarMouseClicked
        
        int row = jt_buscar.getSelectedRow();        // TODO add your handling code here:
        buscar = (Usuario) jt_buscar.getValueAt(row, 0);
    }//GEN-LAST:event_jt_buscarMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        listasolicitud.remove(soli);
        for (Usuario u : lista) {
            if (u == soli.getEmisor()) {
                u.getSolicitudes().remove(soli);
            } else if (u == soli.getReceptor()) {
                u.getSolicitudes().remove(soli);
            }
        }
        try {
            agregar_archivo(use);
        } catch (IOException ex) {
            Logger.getLogger(minifacebook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = (DefaultTableModel) jt_solicitudes.getModel();
        int row = jt_solicitudes.getRowCount();
        for (int i = 0; i < row; i++) {
            ((DefaultTableModel) jt_solicitudes.getModel()).removeRow(0);
        }
        for (Usuario us : lista) {
            if (us == use) {
                for (Solicitudes so : us.getSolicitudes()) {
                    Solicitudes sol[] = {so};
                    model.addRow(sol);
                }
            }
        }
        jt_solicitudes.setModel(model);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jepg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            lb_publicar.setIcon(new ImageIcon(img));
            
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        
        String texto = ta_publicar.getText();
        Icon foto;
        post p = new post();
        p.jl_estado.setText(texto);
        if (lb_publicar.getIcon() != null) {
            foto = lb_publicar.getIcon();
            p.lb_foto.setIcon(foto);
        } else {
            foto = null;
        }
        p.jl_profie.setIcon(use.getFotografia());
        Publicacion publica = new Publicacion(use, p);
        use.getPublicaciones().add(publica);
        for (Usuario usera : use.getAmigos()) {
            usera.getMuro().add(publica);
        }
        ta_publicar.setText("");
        lb_foto.setIcon(null);
        

    }//GEN-LAST:event_jButton9MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Container c = new Container();
        //    c.add(jsc_muro);
        c.setLayout(new GridLayout(0, 1));
        
        for (Publicacion pub : use.getMuro()) {
            post p = pub.getP();
            try {

                //  jsc_muro.setViewportView(p);
                c.add(p);
                
            } catch (Exception e) {
                
            }
            
        }
        jsc_muro.add(c);
        
        try {

//            jsc_muro.getViewport().add(c);
            jsc_muro.getViewport().add(c);
            jif_enviar.setContentPane(jsc_muro);
            jif_enviar.pack();
            jsc_muro.setVisible(true);
            jif_enviar.setResizable(false);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jsc_muro.setVisible(true);
            jif_enviar.setVisible(true);
            jd_inicio.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {

            //jif_enviar.add(jp_enviar);
            jif_enviar.setContentPane(jp_publicar);
            jif_enviar.pack();
            jif_enviar.setResizable(true);
            jif_enviar.setClosable(true);
            jif_enviar.show();
            jDesktopPane1.add(jif_enviar);
            jif_enviar.setVisible(true);
            jp_publicar.setVisible(true);
            jd_inicio.repaint();

            //jd_inicio.add(jDesktopPane1);
            //jif_enviar.setVisible(true);
        } catch (Exception e) {
            
        }
        

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minifacebook.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minifacebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_enviarmensaje;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_vermensajes;
    private com.toedter.calendar.JDateChooser dt_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog jd_inicio;
    private javax.swing.JInternalFrame jif_enviar;
    private javax.swing.JList<String> jl_amigos;
    private javax.swing.JPanel jp_amigos;
    private javax.swing.JPanel jp_buscar;
    private javax.swing.JPanel jp_enviar;
    private javax.swing.JPanel jp_post;
    private javax.swing.JPanel jp_publicar;
    private javax.swing.JPanel jp_solicitudes;
    private javax.swing.JPanel jp_verMensaje;
    private javax.swing.JScrollPane jsc_muro;
    private javax.swing.JTable jt_buscar;
    private javax.swing.JTable jt_solicitudes;
    private javax.swing.JTable jt_ver;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_publicar;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPasswordField pf_login;
    private javax.swing.JTextArea ta_mensajeenviar;
    private javax.swing.JTextArea ta_publicar;
    private javax.swing.JTextField tf_nick;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JMenuItem ver;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> lista = new ArrayList();
    Usuario use = new Usuario();
    ArrayList<Usuario> listabuscar = new ArrayList();
    ArrayList<Solicitudes> listasolicitud = new ArrayList();
    int index = 0;
    Solicitudes soli;
    Usuario buscar;
    
    public void agregararchivo(Usuario u) throws IOException {
        /*FileWriter fw;
        BufferedWriter bw;
         */
        File f = new File("./usuarios/" + u.getNickname());
        f.mkdir();
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream("./usuarios/usuario.txt", false);
            bw = new ObjectOutputStream(fw);
            for (Usuario us : lista) {
                bw.writeObject(us);
            }
            
            try {
                bw.close();
                fw.close();
            } catch (IOException e) {
            }
            
        } catch (IOException e) {
        }
        
    }
    
    public void cargarrarchivo() {
        File f = new File("./usuarios/usuario.txt");
        try {
            lista = new ArrayList();
            Usuario temp = null;
            if (f.exists()) {
                
                FileInputStream entrada = new FileInputStream(f);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                
                try {
                    
                    while ((temp = (Usuario) objeto.readObject()) != null) {
                        lista.add(temp);
                    }
                } catch (EOFException e) {
                }
                objeto.close();
                entrada.close();
            }
            
        } catch (IOException | ClassNotFoundException e) {
            
        }
    }
    
    public void agregar_archivo(Usuario u) throws IOException {
        /*FileWriter fw;
        BufferedWriter bw;
         */
        File f = new File("./usuarios/" + u.getNickname());
        f.mkdir();
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream("./usuarios/usuario.txt", true);
            bw = new ObjectOutputStream(fw);
            for (Usuario us : lista) {
                bw.writeObject(us);
            }
            bw.flush();
            try {
                bw.close();
                fw.close();
            } catch (IOException e) {
            }
            
        } catch (IOException e) {
        }
        
    }
    
    public Usuario getUse() {
        return use;
    }
    
    public void setUse(Usuario use) {
        this.use = use;
    }
}
